// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Service.Data;

#nullable disable

namespace ProductsApi.Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625173125_SeedData2")]
    partial class SeedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ProductsApi.Service.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa640f87-912d-417e-b063-98c40ac1df62"),
                            Description = "Electronic devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("21afa39e-fc53-492b-829b-5ee4fbe93cf8"),
                            Description = "golf clubs and bags",
                            Name = "Golf Equipment"
                        });
                });

            modelBuilder.Entity("ProductsApi.Service.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02d69507-7869-4487-a9f5-e1780a7f856b"),
                            CategoryId = new Guid("21afa39e-fc53-492b-829b-5ee4fbe93cf8"),
                            CreatedAt = new DateTime(2026, 6, 25, 17, 31, 24, 766, DateTimeKind.Utc).AddTicks(7790),
                            IsActive = true,
                            Name = "Yellow Golf Club",
                            Price = 29.989999999999998,
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("ProductsApi.Service.Models.Product", b =>
                {
                    b.HasOne("ProductsApi.Service.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
